version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - mongodb
      - mlflow
      - elasticsearch
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGODB_URI=mongodb://mongodb:27017
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27018:27017"
    command: ["mongod", "--bind_ip_all", "--noauth"]
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
    ports:
      - "9200:9200"
    networks:
      - app-network


  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --host 0.0.0.0 --port 5000
    networks:
      - app-network


volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge




